# -*- coding: utf-8 -*-
"""Data_science_Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vABRXfOplkQLw84gHHbTLiRvq4Jl3719
"""

import pandas as pd
df=pd.read_csv('seed_data.csv')
print(df)

#1st question
import pandas as pd
df=pd.read_csv('seed_data.csv')

# Find the row with the maximum 'Area'
max_area_row = df.loc[df['Area'].idxmax()]

# Extract the variety name and area
highest_variety = max_area_row['Class']
highest_area = max_area_row['Area']

# Output the result
print(f"The wheat variety with the highest 'Area' is '{highest_variety}' with an area of {highest_area}.")

#2nd question
import pandas as pd
# Count the occurrences of each wheat class
class_distribution = df['Class'].value_counts()

# Display the distribution
print("\nDistribution of wheat classes:")
print(class_distribution)
import matplotlib.pyplot as plt

# Plotting the distribution of wheat classes
class_distribution.plot(kind='bar', color=['blue', 'green', 'orange'])
plt.title('Distribution of Wheat Classes')
plt.xlabel('Wheat Class')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.show()

#3rd question
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv("seed_data.csv")


# Histogram of the "Area" distribution
plt.figure(figsize=(10, 6))
plt.hist(df['Area'], bins=20, edgecolor='black')
plt.title('Distribution of Area across Wheat Varieties')
plt.xlabel('Area')
plt.ylabel('Frequency')
plt.grid(axis='y', alpha=0.75)
plt.show()

#4th question
# Select numerical columns
numerical_features = df.select_dtypes(include=["float64", "int64"])

correlation_matrix = numerical_features.corr()

# Visualize the correlation matrix
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(12, 8))
sns.heatmap(correlation_matrix, annot=True, cmap="coolwarm", fmt=".2f", cbar=True)
plt.title("Correlation Matrix of Numerical Features")
plt.show()

#5th question
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Group data by wheat variety and calculate IQR for "Area"
outliers = {}
for variety, group in df.groupby("Class"):
    Q1 = group["Area"].quantile(0.25)  # 25th percentile
    Q3 = group["Area"].quantile(0.75)  # 75th percentile
    IQR = Q3 - Q1  # Interquartile range

    # Calculate bounds for outliers
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    # Identify outliers
    outliers[variety] = group[(group["Area"] < lower_bound) | (group["Area"] > upper_bound)]

# Display outliers for each wheat variety
for variety, outlier_data in outliers.items():
    print(f"\nOutliers for {variety}:")
    print(outlier_data if not outlier_data.empty else "No outliers found.")

# Visualize with boxplot
plt.figure(figsize=(10, 6))
sns.boxplot(data=df, x="Class", y="Area", palette="muted")
plt.title("Boxplot of Area by Wheat Variety (with Outliers)")
plt.xlabel("Wheat Variety")
plt.ylabel("Area")
plt.show()